#!/usr/bin/python
import sys

def trialdiv(n):
    if n < 2: return False
    if n == 2: return True
    if n % 2 == 0: return False
    for x in xrange(3, 1 + int(n ** 0.5), 2):
        if n % x == 0: return False
    return True

def factors(n):
    return [f for f in xrange(1, 1 + int(n ** 0.5)) if n % f == 0]

x = 600851475143
print [f for f in factors(x) if trialdiv(f)][-1]
