#!/usr/bin/python

def chain(n):
    c = []
    m = n
    while m != 1 and m != 89:
        m = sum([int(d)*int(d) for d in str(m)])
        c.append(m)
    return c

max = 10000000
total = 0
for n in xrange(1, max):
    c = chain(n)
    if c:
        if c[-1] == 89:
            total += 1

print total + 1
