#!/usr/bin/ruby

def factorable(n)
    (100..999).each do |m|
        if n % m == 0 and n / m >= 100 and n / m <= 1000 then
            return true
        end
    end
    return false
end

@p = []
range = 999..100
(range.first).downto(range.last).each do |n|
    x = n.to_s.concat(n.to_s.reverse).to_i
    if factorable(x)
        puts x
        break
    end
end
